### ISSUE TITLE
How should protocol parameters be queried?

### ISSUE THREAD

**Issue by jonathanfishbein1** [pbwebdev/cardano-wallet-browser-extensions-interface#1]
Blockfrost return keys with underscords while the code uses keys with camel case.  How do you query protocoal parameters to get camel case keys

**Comment by kermage** [comment]
That you would need to handle manually, see here how I implemented using PHP https://github.com/pbwebdev/cardanopress/blob/2fd8c71fcf498b41ad8dcaf81ba6dc68f31d3700/src/Blockfrost.php#L45-L74

![image](https://user-images.githubusercontent.com/8350223/170171078-84291660-b397-4820-814a-01f6ce8d0e34.png)
