### ISSUE TITLE
I've forked

### ISSUE THREAD

**Issue by jonathanfishbein1** [pbwebdev/cardano-wallet-browser-extensions-interface#2]
I'm creating a typed, functional style, immutable version.  Let me know what you think, one repo is usually better than two

**Comment by pbwebdev** [comment]
Thanks for letting us know @jonathanfishbein1 
We'll review it in the new week.
https://github.com/jonathanfishbein1/cardano-wallet-browser-extensions-interface
@kermage

**Comment by kermage** [comment]
Sorry, am I missing something? Can you please send over a sample snippet of code/screenshot showing it is typed?

All I can see that you did is just simply concatenate the codes into one large TS file.
