### ISSUE TITLE
Support for CardWallet

### ISSUE THREAD

**Issue by pbwebdev** [pbwebdev/cardano-wallet-browser-extensions-interface#3]
Another wallet to support.

https://cwallet.finance/

The team have created a web extension version of their mobile focused wallet:
https://chrome.google.com/webstore/detail/cwallet/apnehcjmnengpnmccpaibjmhhoadaico

**Comment by kermage** [comment]
https://github.com/CardanoPress/cardano-wallet-browser-extensions-interface/compare/v0.4.0...v0.5.0
