### ISSUE TITLE
NuFi wallet Integration

### ISSUE THREAD

**Issue by pbwebdev** [pbwebdev/cardano-wallet-browser-extensions-interface#4]
Look into support for NuFi
https://nu.fi/

Browser extension:
https://chrome.google.com/webstore/detail/nufi/gpnihlnnodeiiaakbikldcihojploeca

**Comment by kermage** [comment]
https://github.com/CardanoPress/cardano-wallet-browser-extensions-interface/compare/v0.4.0...v0.5.0
